name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      id: install
      run: npm ci

    - name: Build
      id: build
      run: npm run build

    - name: Lint
      id: lint
      run: npm run lint

    - name: Run tests
      id: tests
      run: npm run test

    # This will fail the workflow if either of the output directories are different
    # than expected.
    - name: Compare Directories
      id: diff
      run: |
        if [ ! -d cjs/ ]; then
          echo "Expected cjs/ directory does not exist.  See status below:"
          ls -la ./
          exit 1
        fi
        if [ "$(git diff --ignore-space-at-eol --text cjs/ | wc -l)" -gt "0" ]; then
          echo "Detected uncommitted changes after build. See status below:"
          git diff --ignore-space-at-eol --text cjs/
          exit 1
        fi
        if [ ! -d esm/ ]; then
          echo "Expected esm/ directory does not exist.  See status below:"
          ls -la ./
          exit 1
        fi
        if [ "$(git diff --ignore-space-at-eol --text esm/ | wc -l)" -gt "0" ]; then
          echo "Detected uncommitted changes after build. See status below:"
          git diff --ignore-space-at-eol --text esm/
          exit 1
        fi

    # If outdir was different than expected, upload the expected version as a
    # workflow artifact.
    - if: ${{ failure() && steps.diff.outcome == 'failure' }}
      name: Upload Artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: outdir-${{ matrix.node-version }}-diff
        path: |
          cjs/
          esm/
